import { Category, Preset } from "./preset-selector-types";

export const CATEGORIES: Category[] = [
  { id: "small", name: "Small" },
  { id: "medium", name: "Medium" },
  { id: "large", name: "Large" },
  { id: "ambient", name: "Ambient" },
  { id: "favorites", name: "Favorites" },
];

export const PRESETS: Preset[] = [
  // Small presets
  {
    id: "tiny-dancer",
    name: "Tiny dancer",
    category: "small",
    tags: ["Short", "Vocal", "Pop"],
    description: "Fast and tight reverb for vocals that need to stay upfront without dragging.",
  },
  {
    id: "room-for-one",
    name: "Room for one",
    category: "small",
    tags: ["Drums", "Snare", "Tight"],
    description: "Short room vibe that adds punch and presence to snare hits and claps.",
  },
  {
    id: "closet-reverb",
    name: "Closet reverb",
    category: "small",
    tags: ["Dry", "Intimate", "Lo-fi"],
    description: "Gives the illusion of singing in a tight wooden room. Close, dry, and boxy.",
  },
  {
    id: "just-a-whisper",
    name: "Just a whisper",
    category: "small",
    tags: ["Vocal", "Light", "Soft"],
    description: "Barely-there reverb for delicate lead vocals. Featherlight tail.",
  },
  {
    id: "headphones-on",
    name: "Headphones on",
    category: "small",
    tags: ["Lo-fi", "Mono", "Acoustic"],
    description: "Feels like a dorm room recording. Narrow, warm, and vibey.",
  },
  {
    id: "cubicle-blues",
    name: "Cubicle blues",
    category: "small",
    tags: ["Guitar", "Slap", "Compressed"],
    description: "Boxy slap with a touch of grit. Perfect for lo-fi guitar hooks.",
  },
  {
    id: "hats-in-the-hall",
    name: "Hats in the hall",
    category: "small",
    tags: ["Hi-hats", "Percussion", "Room"],
    description: "Short stereo tail ideal for tight percussive transients.",
  },
  {
    id: "studio-a-shower",
    name: "Studio A (shower)",
    category: "small",
    tags: ["Vocal", "Bright", "Room"],
    description: "Crisp bathroom bounce. Adds shine and air to dry takes.",
  },
  {
    id: "dry-ice",
    name: "Dry ice",
    category: "small",
    tags: ["Minimal", "Chill", "FX"],
    description: "Ultra-minimal FX patch. Just enough to chill, not enough to spill.",
  },
  {
    id: "instant-karma",
    name: "Instant karma",
    category: "small",
    tags: ["Short", "Snappy", "Vocal"],
    description: "Fast-acting reflection, inspired by dry Lennon-style slap.",
  },

  // Medium presets
  {
    id: "a-little-too-late",
    name: "A little too late",
    category: "medium",
    tags: ["Vocal", "Dark"],
    description: "Deep and moody reverb with a slow decay. Perfect for atmospheric vocals.",
  },
  {
    id: "bright-white-light",
    name: "Bright white light",
    category: "medium",
    tags: ["Bright", "Vocal"],
    description: "Clear and shimmering reverb that sits well in the mix without muddying.",
  },
  {
    id: "vocal-slap",
    name: "Vocal slap",
    category: "medium",
    tags: ["Vocal", "Slap"],
    description: "Quick slap delay for vocal presence. Adds body without wetness.",
  },
  {
    id: "vocal-slap-deluxe",
    name: "Vocal slap deluxe",
    category: "medium",
    tags: ["Vocal", "Slap", "Dense"],
    description: "Enhanced version with more density and character.",
  },
  {
    id: "fly-on-little-wing",
    name: "Fly on little wing",
    category: "medium",
    tags: ["Guitar", "Bright", "Plate", "Narrow"],
    description: "Feels like walking through the clouds. Narrow and bright, perfect for rhythm guitars.",
  },
  {
    id: "slow-dancing-in-the-ocean",
    name: "Slow dancing in the ocean",
    category: "medium",
    tags: ["Ambient", "Pad", "Wide"],
    description: "Massive ambient space with slow build. Creates an immersive underwater feel.",
  },
  {
    id: "stratocaster-stratosphere",
    name: "Stratocaster/stratosphere",
    category: "medium",
    tags: ["Guitar", "Wide", "Bright"],
    description: "Huge stereo space for clean guitars. Takes your tone to new heights.",
  },
  {
    id: "acoustic-dirtbag",
    name: "Acoustic dirtbag",
    category: "medium",
    tags: ["Guitar", "Acoustic", "Lo-fi"],
    description: "Gritty and lo-fi character for acoustic instruments.",
  },
  {
    id: "bright-as-love",
    name: "Bright as love",
    category: "medium",
    tags: ["Bright", "Short"],
    description: "Quick and sparkly. Adds shine without taking up space.",
  },
  {
    id: "for-slowhands",
    name: "For slowhands",
    category: "medium",
    tags: ["Guitar", "Blues"],
    description: "Classic blues reverb with vintage character.",
  },

  // Large presets
  {
    id: "stadium-dreams",
    name: "Stadium dreams",
    category: "large",
    tags: ["Massive", "Vocal", "Delay"],
    description: "Arena-sized tail. Big vocal ballads and synth leads thrive here.",
  },
  {
    id: "lost-in-berlin",
    name: "Lost in Berlin",
    category: "large",
    tags: ["Techno", "Underground", "Wide"],
    description: "Long metallic reflections perfect for dark, minimal beats.",
  },
  {
    id: "cathedral-crush",
    name: "Cathedral crush",
    category: "large",
    tags: ["Organ", "Drone", "Epic"],
    description: "Huge reflections with soft tails. Ideal for pads and cinematic textures.",
  },
  {
    id: "forever-young",
    name: "Forever young",
    category: "large",
    tags: ["Ballad", "80s", "Wide"],
    description: "Big emotional wash with vintage shimmer. Alphaville core.",
  },
  {
    id: "desert-mirage",
    name: "Desert mirage",
    category: "large",
    tags: ["Guitar", "Slow", "Bright"],
    description: "Bright and ghostly trail, like heat waves on sand. Designed for solo guitars.",
  },
  {
    id: "skyline-tails",
    name: "Skyline tails",
    category: "large",
    tags: ["Ambient", "Clean", "Stereo"],
    description: "Wide stereo trail with urban clarity. Clean and modern.",
  },
  {
    id: "moonroom",
    name: "Moonroom",
    category: "large",
    tags: ["Synth", "Space", "Echo"],
    description: "Ethereal and spongy. Perfect for synths seeking outer orbit.",
  },
  {
    id: "late-checkout",
    name: "Late checkout",
    category: "large",
    tags: ["Keys", "Jazz", "Smooth"],
    description: "Slick, lazy tails. Perfect for Rhodes and smooth jazz layers.",
  },
  {
    id: "canyon-choir",
    name: "Canyon choir",
    category: "large",
    tags: ["Vocal", "Natural", "Wide"],
    description: "Massive reflections with soft modulations. Ideal for solo vocal layers.",
  },
  {
    id: "howling-hills",
    name: "Howling hills",
    category: "large",
    tags: ["Drone", "Texture", "Slow"],
    description: "Long natural decay that howls into silence. Great for intros and outros.",
  },

  // Ambient presets
  {
    id: "purple-haze",
    name: "Purple haze",
    category: "ambient",
    tags: ["Psychedelic", "Slow", "Modulated"],
    description: "Hazy modulated decay that swirls around your mix like smoke.",
  },
  {
    id: "postcard-from-mars",
    name: "Postcard from Mars",
    category: "ambient",
    tags: ["Space", "FX", "Pad"],
    description: "Alien trails and dusty textures. Sounds like a lost signal.",
  },
  {
    id: "infinite-sigh",
    name: "Infinite sigh",
    category: "ambient",
    tags: ["Drone", "Wide", "Calm"],
    description: "Endless decays with soft shimmer. A backdrop of eternal calm.",
  },
  {
    id: "haunted-synth",
    name: "Haunted synth",
    category: "ambient",
    tags: ["Synth", "Dark", "Texture"],
    description: "Dark ambient reverb for spooky synth lines and shadowscapes.",
  },
  {
    id: "glassy-mountains",
    name: "Glassy mountains",
    category: "ambient",
    tags: ["Clean", "Ambient", "Texture"],
    description: "Crystalline reflections with vast width. Inspired by glacial peaks.",
  },
  {
    id: "piano-in-the-fog",
    name: "Piano in the fog",
    category: "ambient",
    tags: ["Piano", "Moody", "Misty"],
    description: "Soft, lo-fi ambiance with dreamy blur. Perfect for soft keys.",
  },
  {
    id: "dune-scape",
    name: "Dune-scape",
    category: "ambient",
    tags: ["Desert", "Ambient", "Film"],
    description: "Evolving tail with dry air feel. Ideal for cinematic scoring.",
  },
  {
    id: "phantom-loop",
    name: "Phantom loop",
    category: "ambient",
    tags: ["FX", "Ghost", "Wide"],
    description: "Echoed ghost trail that loops back on itself subtly.",
  },
  {
    id: "sleeping-city",
    name: "Sleeping city",
    category: "ambient",
    tags: ["Quiet", "Urban", "Night"],
    description: "Still and breathy, like a neon-lit city at 4 AM.",
  },
  {
    id: "riverside-recall",
    name: "Riverside recall",
    category: "ambient",
    tags: ["Field", "Natural", "Organic"],
    description: "Soft environmental tail that feels like nature in rewind.",
  },
];
